import React, { useEffect } from 'react';
import { observer } from 'mobx-react';
import { useQuery, useStore } from '../../../models/RootStore';
import { EntityDescriptorModelType } from '../../../models';

export const EntityDescriptorsFetcher: React.FC = observer(() => {
  const store = useStore();
  const descriptorsQuery = useQuery((store) => store.queryEntityDescriptors({},
    ` type
    categories {
      category
      categoryTitle
      fields { 
        autocomplete {
          type
          value
        }
        lookupTable
        lookupExcludeFields
        fieldName
        queryableName
        label
        fullWidth
        rows
        infoMsgCode
        isManuallyEditable
        isRequired
        isAutoGenerated
        isLifecycleEnvolved
        isCopyable
        isDisabled
        dateGranularity
        updateRules {
          freeze
          value {
            operation {
              type
              fraction
              value
            }
          }
        }
        enumValues {
          dictionary 
        }
        subFields {
          fieldName
          label
          fullWidth
          isManuallyEditable
          isRequired
          isAutoGenerated
          isCopyable
          isDisabled
          enumValues {
            dictionary
          }
          dateGranularity
        }
        validation {
          valueType
          errorMsgCode
          min
          max
          minLength
          maxLength
          pattern
          errorMsgTranslation
          required
          json
        }
        isFilterable {
          participateInFilterPanel
          operation
          order
          validation {
            min
            max
            minLength
            maxLength
            pattern
            valueAsNumber
            valueAsDate
          }
        }
        isBriefField {
          order
        }
        isInfoTooltip
        lookupTableBinding {
          valueFromPropertyName
        }
        dependentField {
          name
          valueFromPropertyName
        }

        default
      }
      __typename
    }`));
  
  useEffect(() => {
    if (!descriptorsQuery.loading) {
      const descriptors = descriptorsQuery.data?.entityDescriptors as EntityDescriptorModelType[];
      store.discreteLayersStore.setEntityDescriptors([...descriptors]);
    }
  }, [descriptorsQuery.data, descriptorsQuery.loading, store.discreteLayersStore]);
  
  return (
    <></>
  );
});
