import React, { useCallback, useMemo } from 'react';
import { useIntl } from 'react-intl';
import { IconButton, Tooltip } from '@map-colonies/react-core';
import { EntityDescriptorModelType, useStore } from '../../models';
import { IDispatchAction } from '../../models/actionDispatcherStore';
import { ILayerImage } from '../../models/layerImage';
import { getFlatEntityDescriptors } from './utils';

interface SaveMetadataProps {
  metadata: ILayerImage;
  className?: string;
}

export const SaveMetadataButton: React.FC<SaveMetadataProps> = ({
  metadata,
  className = ''
}) => {
  const intl = useIntl();
  const store = useStore();

  // Sorting out non-relevant properties from metadata
  const getfFilteredMetadataToDownload = useCallback(() => {
    const descriptors = getFlatEntityDescriptors(
      metadata,
      store.discreteLayersStore.entityDescriptors as EntityDescriptorModelType[]
    );

    const pureMetadata = Object.fromEntries(
      Object.entries(metadata).filter(([key]) => {
        // Filter out auto-generated fields and map to metadata property names.
        const creationFieldsNames = descriptors
          .filter((descriptor) => !(descriptor.isAutoGenerated as boolean))
          .map((descriptor) => descriptor.fieldName);

        return creationFieldsNames.includes(key);
      })
    );

    return pureMetadata;
  }, [metadata]);

  const filteredMetadataToDownload = useMemo(getfFilteredMetadataToDownload, [metadata]);

  const dispatchAction = (action: Record<string, unknown>): void => {
    store.actionDispatcherStore.dispatchAction(
      {
        action: action.action,
        data: action.data,
      } as IDispatchAction
    );
  };

  const metadataExporter = useMemo((): JSX.Element => {
    return (
      <Tooltip
        content={intl.formatMessage({ id: 'action.save-metadata.tooltip' })}
      >
        <IconButton
          className={`mc-icon-Status-Downloads glow-missing-icon ${className}`}
          label="save-metadata"
          onClick={(): void =>
             dispatchAction({ action: `${metadata.__typename}.save-metadata`, data: filteredMetadataToDownload })
          }
        />
      </Tooltip>
    );
  }, [metadata]);

  return metadataExporter;
};
