/* eslint-disable @typescript-eslint/naming-convention */
export const Country = {
  UGA: { en: "UGANDA", he: "אוגנדה" },
  UZB: { en: "UZBEKISTAN", he: "אוזבקיסטן" },
  AUT: { en: "AUSTRIA", he: "אוסטריה" },
  AUS: { en: "AUSTRALIA", he: "אוסטרליה" },
  UKR: { en: "UKRAINE", he: "אוקראינה" },
  URY: { en: "URUGUAY", he: "אורגוואי" },
  AZE: { en: "AZERBAIJAN", he: "אזרביג'אן" },
  ARE: { en: "UNITED ARAB EMIR", he: "איחוד האמירויות הערבית" },
  ITA: { en: "ITALY", he: "איטליה" },
  VIR: { en: "VIRGIN ISLAND", he: "איי הבתולה" },
  WLF: { en: "WALLIS FUTUNA ISL", he: "איי ווליס ופוטונה "},
  TCA: { en: "TORKAS ISLAND", he: "איי טורקס וקייקוס" },
  MHL: { en: "MARSHALL ISLANDS", he: "איי מרשל" },
  NFK: { en: "NORFOLK ISLA", he: "איי נורפולק" },
  SYC: { en: "SEYCHELLES", he: "איי סיישל" },
  FLK: { en: "FALKLAND", he: "איי פוקלנד" },
  FJI: { en: "FIJI", he: "איי פיגי" },
  COM: { en: "COMOROS ISLANDS", he: "איי קומורו" },
  COK: { en: "COOK ISL", he: "איי קוק" },
  CYM: { en: "CAYMAN ISLANDS", he: "איי קיימן" },
  CPV: { en: "CAPE VERDE ISLANDS", he: "איי קייפ וורדה" },
  SLB: { en: "SOLOMON ISLANDS", he: "איי שלמה הבריטיים" },
  IDN: { en: "INDONESIA", he: "אינדונזיה" },
  ISL: { en: "ICELAND", he: "איסלנד" },
  IRL: { en: "IRELAND", he: "אירלנד" },
  IRN: { en: "IRAN", he: "אירן" },
  SLV: { en: "EL SALVADOR", he: "אל סלבדור" },
  ALB: { en: "ALBANIA", he: "אלבניה" },
  DZA: { en: "ALGERIA", he: "אלג'יריה" },
  AGO: { en: "ANGOLA", he: "אנגולה" },
  AND: { en: "ANDORRA", he: "אנדורה" },
  ATG: { en: "ANTIGUA AND BARBUDA", he: "אנטיגואה וברבודה" },
  EST: { en: "ESTONIA", he: "אסטוניה" },
  AFG: { en: "AFGHANISTAN", he: "אפגניסטן" },
  ECU: { en: "ECUADOR", he: "אקוואדור" },
  ARG: { en: "ARG ENTINA", he: "ארגנטינה" },
  ERI: { en: "ERITREA", he: "אריתראה" },
  ARM: { en: "ARM ENIA", he: "ארמניה" },
  USA: { en: "UNITED STATES", he: "ארצות הברית" },
  ETH: { en: "ETHIOPIA", he: "אתיופיה" },
  BHS: { en: "BAHAMAS", he: "בהמס" },
  BTN: { en: "BHUTAN", he: "בוטן" },
  BWA: { en: "BOTSWANA", he: "בוטסוואנה" },
  BGR: { en: "BULGARIA", he: "בולגריה" },
  BOL: { en: "BOLIVIA", he: "בוליביה" },
  BIH: { en: "BOSNIA HERZEGOVINA", he: "בוסניה הרצגובינה" },
  BDI: { en: "BURUNDI", he: "בורונדי" },
  BFA: { en: "BURKINA FASSO", he: "בורקינה פאסו" },
  BHR: { en: "BAHREIN", he: "בחריין" },
  BLR: { en: "BELARUS", he: "בלורוסיה" },
  BEL: { en: "BELGIUM", he: "בלגיה" },
  BLZ: { en: "BELIZE", he: "בליז" },
  BGD: { en: "BANGLADESH", he: "בנגלדש" },
  BEN: { en: "BENIN DAHOMEY", he: "בנין דהומ" },
  BRB: { en: "BARBADOS", he: "ברבדוס" },
  BRN: { en: "BRUNEI", he: "ברוניי" },
  BRA: { en: "BRAZIL", he: "ברזיל" },
  BMU: { en: "BERMUDA", he: "ברמודה" },
  GEO: { en: "GEORGIA", he: "גאורגיה" },
  GHA: { en: "GHANA", he: "גאנה" },
  GAB: { en: "GABON", he: "גבון" },
  GLP: { en: "GUADELOUPE", he: "גואדאלופ" },
  GUM: { en: "GUAM", he: "גואם" },
  GTM: { en: "GUATEMALA", he: "גווטאמלה" },
  GUY: { en: "GUYANA", he: "גויאנה" },
  GUF: { en: "FR ENCH GUIANA", he: "גויאנה הצרפתית" },
  DJI: { en: "DJIBOUTI", he: "גיבוטי" },
  GIB: { en: "GIBRALTAR", he: "גיברלטר" },
  GIN: { en: "GUINEA", he: "גינאה" },
  GNB: { en: "GUINEA BISSAU", he: "גינאה ביסאו" },
  GNQ: { en: "GUINEA EQ", he: "גינאה המשוונית" },
  GMB: { en: "GAMBIA", he: "גמביה" },
  JAM: { en: "JAMAICA", he: "ג'מייקה" },
  DEU: { en: "GERMANY", he: "גרמניה" },
  GRD: { en: "GR ENADA", he: "גרנדה" },
  DMA: { en: "DOMINICA", he: "דומיניקה" },
  DNK: { en: "D ENMARK", he: "דנמרק" },
  ZAF: { en: "SOUTH AFRICA", he: "דרום אפריקה" },
  SSD: { en: "REPUBLIC OF SOUTH SUDAN", he: "דרום סודאן" },
  HTI: { en: "HAITI", he: "האיטי" },
  IND: { en: "INDIA", he: "הודו" },
  NLD: { en: "NETHERLANDS", he: "הולנד" },
  HKG: { en: "HONG KONG", he: "הונג קונג" },
  HUN: { en: "HUNGARY", he: "הונגריה" },
  HND: { en: "HONDURAS", he: "הונדורס" },
  GBR: { en: "UNITED KINGDOM", he: "הממלכה המאוחדת" },
  DOM: { en: "DOMINICAN REPUBLIC", he: "הרפובליקה הדומיניקנית" },
  CAF: { en: "C ENTRAL AFRICAN REPUBLIC", he: "הרפובליקה המרכז אפריקנית" },
  AYOSH: { en: "PALESTINIAN AUTHORITY AYOSH", he: "הרשות הפלסטינית איוש" },
  GAZA: { en: "PALESTINIAN AUTHORITY GAZA", he: "הרשות הפלסטינית עזה" },
  VNM: { en: "VIETNAM", he: "ויטנאם" },
  VUT: { en: "VANUATU", he: "ונואטו" },
  VEN: { en: "VENEZUELA", he: "ונצואלה" },
  ZWE: { en: "ZIMBABWE", he: "זימבאבווה" },
  ZMB: { en: "ZAMBIA", he: "זמביה" },
  CIV: { en: "IVORY COAST", he: "חוף השנהב" },
  TJK: { en: "TAJIKISTAN", he: "טג'יקיסטאן" },
  TUV: { en: "TUVALU", he: "טובלו" },
  TGO: { en: "TOGO", he: "טוגו" },
  TON: { en: "TONGA", he: "טונגה" },
  TWN: { en: "TAIWAN", he: "טיוואן" },
  TZA: { en: "TANZANIA", he: "טנזניה" },
  TTO: { en: "TRINIDAD AND TOBAGO", he: "טרינידד וטובגו" },
  SER: { en: "YUGOSLAVIA", he: "יוגוסלביה" },
  GRC: { en: "GREECE", he: "יוון" },
  JPN: { en: "JAPAN", he: "יפן" },
  JOR: { en: "JORDAN", he: "ירדן" },
  ISR: { en: "ISRAEL", he: "ישראל" },
  KWT: { en: "KUWAIT", he: "כווית" },
  UNKNOWN: { en: "UNKNOWN", he: "לא ידוע" },
  LAO: { en: "LAOS", he: "לאוס" },
  LBN: { en: "LEBANON", he: "לבנון" },
  LBY: { en: "LIBYA", he: "לוב" },
  LUX: { en: "LUXEMBOURG", he: "לוכסמבורג" },
  LVA: { en: "LATVIA", he: "לטביה" },
  LBR: { en: "LIBERIA", he: "ליבריה" },
  LTU: { en: "LITHUANIA", he: "ליטא" },
  LIE: { en: "LIECHT ENSTEIN", he: "ליכטנשטיין" },
  LSO: { en: "LESOTHO", he: "לסוטו" },
  MRT: { en: "MAURITANIA", he: "מאוריטניה" },
  MUS: { en: "MAURITIUS", he: "מאוריציוס" },
  MLI: { en: "MALI", he: "מאלי" },
  MDG: { en: "MADAGASCAR", he: "מדגסקר" },
  MOZ: { en: "MOZAMBIQUE", he: "מוזמביק" },
  MDA: { en: "MOLDOVA", he: "מולדובה" },
  MNG: { en: "MONGOLIA", he: "מונגוליה" },
  MNE: { en: "MONT ENEGRO", he: "מונטנגרו" },
  MSR: { en: "MONTSERRAT", he: "מונסרת" },
  MCO: { en: "MONACO", he: "מונקו" },
  TMP: { en: "EAST TIMOR", he: "מזרח טימור" },
  MMR: { en: "MYANMAR BURMA", he: "מיאנמר בורמה" },
  FSM: { en: "MICRONESIA", he: "מיקרונזיה" },
  MWI: { en: "MALAWI", he: "מלאווי" },
  MDV: { en: "MALADIVES", he: "מלדיבים" },
  MYS: { en: "MALAYSIA", he: "מלזיה" },
  MLT: { en: "MALTA", he: "מלטה" },
  EGY: { en: "EGYPT", he: "מצרים" },
  MAC: { en: "MACAO", he: "מקאו" },
  MKD: { en: "MACEDONIA", he: "מקדוניה" },
  MEX: { en: "MEXICO", he: "מקסיקו" },
  MAR: { en: "MOROCCO", he: "מרוקו" },
  MTQ: { en: "MARTINIQUE", he: "מרטיניק" },
  NRU: { en: "NAURU", he: "נאורו" },
  NOR: { en: "NORWAY", he: "נורבגיה" },
  NER: { en: "NIGER", he: "ניגר" },
  NGA: { en: "NIGERIA", he: "ניגריה" },
  NZL: { en: "NEW ZEALAND", he: "ניו זילנד" },
  NIC: { en: "NICARAGUA", he: "ניקרגואה" },
  NAM: { en: "NAMIBIA", he: "נמיביה" },
  NPL: { en: "NEPAL", he: "נפאל" },
  STP: { en: "SAO TOME AND PRINCIP", he: "סאו טומה ופרינציפה" },
  SDN: { en: "SUDAN", he: "סודן" },
  SWZ: { en: "SWAZILAND", he: "סווזילנד" },
  SOM: { en: "SOMALIA", he: "סומליה" },
  SYR: { en: "SYRIA", he: "סוריה" },
  SUR: { en: "SURINAME", he: "סורינם" },
  SHN: { en: "ST HEL ENA", he: "סט הלנה" },
  VCT: { en: "ST VINC ENT", he: "סט וינסנט" },
  LCA: { en: "ST LUCIA", he: "סט לוציה" },
  KNA: { en: "ST KITTS NEVIS", he: "סט קיטס ונביס" },
  SLE: { en: "SIERRA LEONE", he: "סיירה ליאונה" },
  CHN: { en: "CHINA", he: "סין" },
  SGP: { en: "SINGAPORE", he: "סינגפור" },
  SIK: { en: "SIKKIM", he: "סיקים" },
  SVN: { en: "SLOV ENIA", he: "סלובניה" },
  SVK: { en: "SLOVAKIA", he: "סלובקיה" },
  WSM: { en: "SAMOA", he: "סמואה" },
  ASM: { en: "AMERICAN SAMOA", he: "סמואה האמריקאי" },
  SMR: { en: "SAN MARINO", he: "סן מרינו" },
  SEN: { en: "S ENEGAL", he: "סנגל" },
  ESP: { en: "SPAIN", he: "ספרד" },
  SRB: { en: "SERBIA", he: "סרביה"},
  LKA: { en: "SRI-LANKA", he: "סרי לנקה צילו" },
  OMN: { en: "OMAN", he: "עומן" },
  IRQ: { en: "IRAQ", he: "עירק" },
  SAU: { en: "SAUDI ARABIA", he: "ערב הסעודית" },
  POL: { en: "POLAND", he: "פולין" },
  PYF: { en: "FR ENCH POLYNESIA", he: "פולינזיה הצרפתית" },
  PRI: { en: "PUERTO RICO", he: "פורטו ריקו" },
  PRT: { en: "PORTUGAL", he: "פורטוגל" },
  PHL: { en: "PHILIPPINES", he: "פיליפינים" },
  FIN: { en: "FINLAND", he: "פינלנד" },
  PLW: { en: "PALAU", he: "פלאו" },
  PAN: { en: "PANAMA", he: "פנמה"},
  PNG: { en: "PAPUA NEW GUINEA", he: "פפואה גינאה החדשה" },
  PAK: { en: "PAKISTAN", he: "פקיסטן" },
  PRY: { en: "PARAGUAY", he: "פרגוואי" },
  PER: { en: "PERU", he: "פרו" },
  TCD: { en: "CHAD", he: "צ'אד" },
  CHL: { en: "CHILE", he: "צ'ילה" },
  CSK: { en: "CZECHOSLOVAKIA", he: "צ'כוסלובקיה" },
  CZE: { en: "CZECH REPUBLIC", he: "צ'כיה" },
  FRA: { en: "FRANCE", he: "צרפת" },
  CUB: { en: "CUBA", he: "קובה" },
  COL: { en: "COLOMBIA", he: "קולומביה" },
  COG: { en: "CONGO DEMO REP", he: "קונגו רפובליקה דמוקרטית" },
  CRI: { en: "COSTA RICA", he: "קוסטה ריקה" },
  KOR: { en: "S KOREA", he: "קוריאה הדרומית" },
  PRK: { en: "N KOREA", he: "קוריאה הצפונית" },
  KAZ: { en: "KAZAKHSTAN", he: "קזחסטאן" },
  QAT: { en: "QATAR", he: "קטר" },
  KGZ: { en: "KIRGHIZSTAN", he: "קירגיזסטאן" },
  KIR: { en: "KIRIBATI", he: "קיריבטי" },
  NCL: { en: "NEW CALEDONIA", he: "קלדוניה החדשה" },
  KHM: { en: "CAMBODIA", he: "קמבודיה" },
  CMR: { en: "CAMEROON", he: "קמרון" },
  CAN: { en: "CANADA", he: "קנדה" },
  KEN: { en: "KENYA", he: "קניה" },
  CYP: { en: "CYPRUS", he: "קפריסין" },
  HRV: { en: "CROATIA", he: "קרואטיה" },
  REU: { en: "REUNION", he: "ראוניון" },
  RWA: { en: "RWANDA", he: "רואנדה" },
  ROM: { en: "ROMANIA", he: "רומניה" },
  RUS: { en: "RUSSIAN FEDERATION", he: "רוסיה" },
  SWE: { en: "SWED EN", he: "שוודיה" },
  CHE: { en: "SWITZERLAND", he: "שוויץ" },
  THA: { en: "THAILAND", he: "תאילנד" },
  TUN: { en: "TUNISIA", he: "תוניסיה" },
  TUR: { en: "TURKEY", he: "תורכיה" },
  TKM: { en: "TURKM ENISTAN", he: "תורכמניסטאן" },
  YEM: { en: "YEM EN", he: "תימן" }
};