export enum LinkType {
  WMTS_LAYER = 'WMTS_LAYER',
  XYZ_LAYER = 'XYZ_LAYER',
  THREE_D_LAYER = '3D_LAYER',
  THREE_D_TILES = '3DTiles',
  TERRAIN_QMESH = 'TERRAIN_QMESH',
  WMTS = 'WMTS',
  WMS = 'WMS',
  WCS = 'WCS',
  THUMBNAIL_S = 'THUMBNAIL_S',
  THUMBNAIL_M = 'THUMBNAIL_M',
  THUMBNAIL_L = 'THUMBNAIL_L',
  LEGEND_DOC = 'LEGEND_DOC',
  LEGEND_IMG = 'LEGEND_IMG',
  LEGEND = 'LEGEND'
}