import { EntityDescriptorModelType } from '../../../models';
import { getFlatEntityDescriptors } from '../utils';

const PP_COMMON_PARAMS = ['resolutionMeter', 'resolutionDegree'];

export const getUIIngestionFieldDescriptors = (entityDescriptors: EntityDescriptorModelType[]) => {
  return getFlatEntityDescriptors('PolygonPartRecord', entityDescriptors)
    .filter((desc) => PP_COMMON_PARAMS.includes(desc.fieldName as string))
    .map(desc => {
      return {
        ...desc,
        isRequired: true,
        isAutoGenerated: false,
        infoMsgCode: ['info-general-tooltip.required'],
      }
    });
};